version: '3.8'

services:
  # Frontend Web Server
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - e-commerce-network
    restart: unless-stopped

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=${MONGODB_URI_PRODUCT}
    networks:
      - e-commerce-network
    restart: unless-stopped

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=${MONGODB_URI_ORDER}
    networks:
      - e-commerce-network
    restart: unless-stopped

networks:
  e-commerce-network:
    driver: bridge